## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

title = "Jordyn Jones"
copyright = "{year}"

## -----------------------------------------------
## Publish
## -----------------------------------------------

relativeURLs = "true"
#canonifyURLs = "true"

# Local
baseURL = "/"
publishDir = "docs"

# Remote
#baseURL = "https://jadewink.github.io/"
#publishDir = "docs"

## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "G-XXXXXXXXXX"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]
  description = "A (modular, highly tweakable) responsive one-page theme for Hugo"
  logo = "images/banner.jpg"
  favicon = true

[Params.social]
  github = "https://github.com/jadewink/"
  twitter = "https://twitter.com/jadewinkdotcom"
  email = "jordynjones@gmail.com"
  instagram = "https://instagram.com/jadewink"
  linkedin = "https://linkedin.com/in/jordynxjones"

[Params.asset]
  fontawesome_css = ["css/fontawesome-all.min.css"]
  fontawesome_js = ["js/fontawesome-all.min.js"]